apiVersion: v1
kind: Namespace
metadata:
  name: cfc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfcbackend
  namespace: cfc
  labels:
    app: cfcbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cfcbackend
  template:
    metadata:
      name: cfcbackend  
      namespace: cfc  
      labels:
        app: cfcbackend
    spec:
      containers:
      - name: cfcbackend
        image: developersthought/cfcbackend:latest
        imagePullPolicy: Always
        env:
        - name: CLOUDANT_ID
          value: "<CLOUDANT_ID>"
        - name: CLOUDANT_IAM_APIKEY
          value: "<CLOUDANT_IAM_APIKEY>"    
---
apiVersion: v1
kind: Service
metadata:
  name: cfcbackend
  namespace: cfc
  labels:
    app: cfcbackend
spec:
  type: NodePort  
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: cfcbackend